version: '3.8'
services:
  crudphp:
    container_name: crudphp
    image: legnakra/crudphp
    restart: always
    environment:
      DB_NAME: crudphp
      DB_USER: crudphp
      DB_PASSWORD: crudphp
      DB_HOST: bd_mariadb
    ports:
      - 8081:80
    depends_on:
      - db
  db:
    container_name: bd_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: crudphp
      MARIADB_USER: crudphp
      MARIADB_PASSWORD: crudphp
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:
